### ISSUE TITLE
DFD Comments October 3

### ISSUE THREAD

**Issue by germonprez** [adorcy/3420ISQAAssignment1#28]
Hi Aaron, 

Here are a few comments: 

1) Going to OSS Component DB should be Software Package License and Vulnerability Results (not just licenses). 

2) Same comments holds true when returning information to the Developer 

3) Same comment holds true when the Manager is requesting Project and License Information. This should include Vulnerabilities too. Same with the response to the Manager. And, the same holds true when the Developer queries for Software Project information. Just don't forget vulnerabilities in these. 

4) Policy document information to be updated or modified --should be--> Policy document information to be created or modified. 

Outside of these very simple editorial issues, the DFD looks good structurally. Well done. 

MG

**Comment by adorcy** [comment]
![dfd 4th draft](https://cloud.githubusercontent.com/assets/21319727/19096123/bde57df8-8a5f-11e6-9a8c-b155de5986ba.PNG)
