### ISSUE TITLE
DFD Comments #1

### ISSUE THREAD

**Issue by germonprez** [adorcy/3420ISQAAssignment1#7]
Make sure you put a data label on the dataflow going to the DB. 

<img width="194" alt="screen shot 2016-09-09 at 12 36 13 pm" src="https://cloud.githubusercontent.com/assets/656208/18396597/23224d0c-768a-11e6-8401-ef73730428b7.png">

**Comment by adorcy** [comment]
Thank you. This issue has been fixed in my most recent DFD submission.
